[package]
name = "lime_wm"
version = "0.0.1"
authors = ["Victor Berger <victor.berger@m4x.org>", "Drakulix (Victoria Brekenfeld)"]
license = "MIT"
publish = false
edition = "2021"

[dependencies]
bitflags = "1.2.1"
thiserror = "1"
xcursor = { version = "0.3.3", optional = true }
image = { version = "0.24.0", default-features = false, optional = true }
fps_ticker = { version = "1.0.0", optional = true }
rand = "0.8"
slog = { version = "2.1.1" }
slog-term = "2.8"
slog-async = "2.2"
slog-stdlog = "4.1.0"
slog-scope = "4.4.0"
xkbcommon = "0.4.0"

[dependencies.smithay]
git = "https://github.com/Smithay/smithay"
rev = "32d9be7"
default-features = false
features = [
    "desktop",
    "wayland_frontend",
    "slog-stdlog",
    "backend_libinput",
    "backend_udev",
    "backend_drm",
    "backend_gbm",
    "backend_egl",
    "backend_session",
    "renderer_gl",
    "renderer_multi",
]

[dependencies.x11rb]
optional = true
version = "0.10.0"
default-features = false
features = [ "composite" ]

[build-dependencies]
gl_generator = "0.14"

[features]
default = [ "egl", "logind", "xwayland", "image", "xcursor" ]
egl = [ "smithay/use_system_lib", "smithay/backend_egl" ]
logind = [ "smithay/backend_session_logind" ]
elogind = ["logind", "smithay/backend_session_elogind" ]
libseat = ["smithay/backend_session_libseat" ]
xwayland = [ "smithay/xwayland", "x11rb", "smithay/x11rb_event_source" ]
debug = [ "fps_ticker", "image/png" ]
test_all_features = ["default", "debug"]
